server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://serverdbcripto.mysql.database.azure.com:3306/criptoboot?useSSL=true
    username: admCripto
    password: Cripto$1987
  jpa:
    hibernate:
      ddl-auto: update